# Generated by Django 4.2.19 on 2025-02-25 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_watchlist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('user', 'listing')},
        ),
    ]
